Repository pinatacolada/topskylppc, pull requests merged in 2019-10, with the labels that each got.

#30 Updated stand rules
  topsky/GRpluginStands.txt
Labels: Feature

#31 pretty colors
  topsky/TopSkyMaps.txt
  topsky/TopSkySettings.txt
  topsky/TopSkySymbols.txt
  topsky/TopSkyViews.txt
Labels: Feature

#32 ASR files
  LPPC_CTR.asr
  LPPT_GND_TSGR.asr
Labels: Feature

#35 Fixes #34
  LPPT_GND_TSGR.asr
Labels: Fix

#33 Tags and lists
  LPPC/ASR/LPPC_CTR.asr
  LPPC/ASR/LPPT_GND_TSGR.asr
  Settings/DepartureList_TopSky.txt
  Settings/General.txt
  Settings/Plugins.txt
  Settings/SectorExitList_TopSky.txt
  Settings/SectorInboundList_TopSky.txt
  Settings/Symbology.txt
  Settings/Tags.txt
  Settings/VACCAUT_SETTINGS_ARL.txt
  topsky/GRpluginSettings.txt
  topsky/TopSkyAreas.txt
  topsky/TopSkyAreasManualAct.txt
  topsky/TopSkySettings.txt
Labels: Feature, Tweak

#45 actually writes a readme
  README.md
Labels: Documentation

#46 oops
  README.md
Labels: Fix, Working as Intended™

#48 Update Readme
  README.md
Labels: Documentation, Fix
