Repository pinatacolada/topskylppc, pull requests merged in 2020-12, with the labels that each got.

#207 Fixes LPPR incorrect GR display
  LPPC/Plugins/topsky/GRpluginMaps.txt
Labels: Fix

#209 Upper sectors maps
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#210 Remove LPPT OM03
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#211 Nudges VSI indicator in approach window
  LPPC/Plugins/topsky/GRpluginSettings.txt
Labels: Fix

#212 More DELFAR less RT REROUTE
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature, Tweak

#213 Auto URB map for porto app
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#214 Fixes missplaced spanish areas labels
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix
