Repository pinatacolada/topskylppc, pull requests merged in 2020-10, with the labels that each got.

#137 TopSky 2.3.1 and GroundRadar 1.3
  LPPC/ASR/LPMA_GND.asr
  LPPC/ASR/LPMA_GND_TSGR.asr
  LPPC/ASR/LPPC_CTR_TS.asr
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - Developer Guide.pdf
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - General.pdf
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - Version History.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Coordination.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Data Link Functions.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Developer Guide.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - General.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.docx
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Version History.pdf
  LPPC/Plugins/topsky/GRplugin.dll
  LPPC/Plugins/topsky/GRpluginMaps.txt
  LPPC/Plugins/topsky/GRpluginOperatorInfo.txt
  LPPC/Plugins/topsky/GRpluginSettings.txt
  LPPC/Plugins/topsky/GRpluginStands.txt
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkyCallsigns.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Plugins/topsky/TopSkySettingsLocal.txt
  LPPC/Plugins/topsky/TopSkySymbols.txt
  LPPC/Plugins/topsky/TopSky_Developer_Guide_Settings.xlsx
  LPPC/Settings/DepartureList_TopSky.txt
  LPPC/Settings/FPList_TopSky.txt
  LPPC/Settings/General_TopSky.txt
  LPPC/Settings/Screen_TopSky.txt
  LPPC/Settings/SectorExitList_TopSky.txt
  LPPC/Settings/SectorInboundList_TopSky.txt
  LPPC/Settings/Symbology_TopSky.txt
  LPPC/Settings/Tags_TopSky.txt
  LPPC_CTR_TS.prf
Labels: Documentation, Feature, Fix, Update

#138 Adds Segregated Airspace to the manual
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.docx
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.pdf
Labels: Documentation, Fix

#142 bananas
  LPPC/ASR/LPMA_GND_TSGR.asr
  LPPC/Settings/FPList_TopSky.txt
Labels: Working as Intended™

#143 Fixes symbols
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySymbols.txt
Labels: Fix

#144 Fixes ground radars not showing background grey
  LPPC/ASR/LPFR_GND_TSGR.asr
  LPPC/ASR/LPPR_GND_TSGR.asr
Labels: Fix

#145 Fixes neighbor CPDLC
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Fix

#147 Adds Nortavia training areas to URB map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#149 Bug fixes of varied order
  LPPC/Plugins/topsky/GRpluginStands.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#152 Madeira Ground Radar
  LPPC/Plugins/topsky/GRpluginStands.txt
Labels: Feature

#153 Improved accuracy R42A and B definition
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#155 Refine LPPT TMA
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#156 Cleaned LPMA, LPPS and LPFR CTR
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#157 Update LPCS and LPPT CTR
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#159 Added N and S points to PCAS, Added ENACI to POINTS
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature, Fix

#167 Fixes Neverland and Snowfall not showing SFL
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix

#166 Added Algarve drones
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Feature, Tweak

#154 Ground Radar version 1.4.2
  .gitignore
  LPPC/ASR/LPFR_GND_TSGR.asr
  LPPC/ASR/LPPR_GND_TSGR.asr
  LPPC/ASR/LPPT_GND_TSGR.asr
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - Developer Guide.pdf
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - General.pdf
  LPPC/Plugins/topsky/GRplugin.dll
  LPPC/Plugins/topsky/GRpluginAircraftInfo.txt
  LPPC/Plugins/topsky/GRpluginMaps.txt
  LPPC/Plugins/topsky/GRpluginSettings.txt
  LPPC/Plugins/topsky/GRpluginStands.txt
Labels: Feature, Tweak, Update

#168 Tweaks non radared airports
  LPPC/ASR/LPCS_TWR.asr
  LPPC/ASR/LPFR_GND_TSGR.asr
  LPPC/ASR/LPMA_GND_TSGR.asr
  LPPC/Plugins/topsky/GRpluginSettings.txt
Labels: Fix, Tweak

#171 Update ROT U airway comments with new designators
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#170 Update TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Feature

#172 Tweaks segregated areas
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Feature, Fix, Tweak

#174 Fixes A3233/20 being active h24
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix
