Repository pinatacolada/topskylppc, pull requests merged in 2020-02, with the labels that each got.

#77 Ground Radar finally done yay
  LPPC/ASR/LPPT_GND_TSGR.asr
  topsky/GRpluginMaps.txt
  topsky/GRpluginSettings.txt
  topsky/GRpluginStands.txt
  topsky/TopSkyAreasManualAct.txt
  topsky/TopSky_Developer_Guide_Settings.xlsx
Labels: Documentation, Feature, Fix, Tweak

#80 Fixes #78
  topsky/GRpluginStands.txt
Labels: Fix

#88 Areas 12 February
  topsky/TopSkyAreasManualAct.txt
Labels: Feature

#75 LPPC_ASR
  LPPC/ASR/LPMA_APP.asr
  LPPC/ASR/LPPC_CTR.asr
  LPPC/ASR/LPPT_APP.asr
Labels: Feature

#89 Update TopSkyAreas.txt
  topsky/TopSkyAreas.txt
Labels: Fix

#90 Update TopSkyAreas.txt
  topsky/TopSkyAreas.txt
Labels: Fix

#91 Update TopSkyAreas.txt
  topsky/TopSkyAreas.txt
Labels: Fix

#92 N1 closed
  topsky/GRpluginMaps.txt
Labels: Tweak

#93 beta bug fixes
  LPPC/Settings/SectorExitList_TopSky.txt
  LPPC/Settings/SectorInboundList_TopSky.txt
  LPPC/Settings/Tags_TopSky.txt
  topsky/TopSkySettings.txt
Labels: Beta testing, Fix

#94 Updates CPDLC positions
  topsky/TopSkyCPDLC.txt
Labels: Tweak

#95 FUA 20 Feb
  topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#96 Update Snowfall and Neverland with spanish border
  topsky/TopSkyAreas.txt
Labels: Fix

#98 scratch
  LPPC/Settings/DepartureList_TopSky.txt
  LPPC/Settings/SectorExitList_TopSky.txt
  LPPC/Settings/SectorInboundList_TopSky.txt
Labels: Tweak

#99 fua21feb
  topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#100 remove stand menu
  LPPC/Settings/DepartureList_TopSky.txt
Labels: Fix

#97 Documentation
  topsky/Documentation/Ground Radar plugin for EuroScope - Developer Guide.pdf
  topsky/Documentation/Ground Radar plugin for EuroScope - General.pdf
  topsky/Documentation/Ground Radar plugin for EuroScope - Version History.pdf
  topsky/Documentation/TopSky plugin for EuroScope - Coordination.pdf
  topsky/Documentation/TopSky plugin for EuroScope - Data Link Functions.pdf
  topsky/Documentation/TopSky plugin for EuroScope - Developer Guide.pdf
  topsky/Documentation/TopSky plugin for EuroScope - General.pdf
  topsky/Documentation/TopSky plugin for EuroScope - Portugal.docx
  topsky/Documentation/TopSky plugin for EuroScope - Portugal.pdf
  topsky/Documentation/TopSky plugin for EuroScope - Version History.pdf
  topsky/TopSky plugin for EuroScope - Denmark+Sweden.pdf
  topsky/TopSky plugin for EuroScope - Finland.pdf
Labels: Documentation

#101 Fua24feb
  topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#102 Update NOTAM provider
  topsky/TopSkySettings.txt
Labels: Fix
