Repository pinatacolada/topskylppc, pull requests merged in 2020-01, with the labels that each got.

#67 Update LPFR_APP.asr
  LPPC/ASR/LPFR_APP.asr
Labels: Feature

#66 CPDLC
  LPPC/ASR/LPPC_CTR.asr
  LPPC/ASR/LPPT_GND_TSGR.asr
  LPPC/Settings/DepartureList_TopSky.txt
  LPPC/Settings/SectorExitList_TopSky.txt
  LPPC/Settings/SectorInboundList_TopSky.txt
  LPPC/Settings/Tags.txt
  topsky/TopSkyCPDLC.txt
  topsky/TopSkyCPDLChoppieCode.txt
  topsky/TopSkySettings.txt
Labels: Feature

#69 updates colors
  LPPC/Settings/Symbology.txt
Labels: Fix

#70 updates some ASRs
  LPPC/ASR/LPFR_TWR.asr
  LPPC/ASR/LPMA_TWR.asr
  LPPC/ASR/LPPC_CTR.asr
  LPPC/ASR/LPPR_TWR.asr
Labels: Fix

#71 Bunch of changes
  LPPC/ASR/LPFR_TWR.asr
  LPPC/ASR/LPMA_TWR.asr
  LPPC/ASR/LPPC_CTR.asr
  LPPC/ASR/LPPR_TWR.asr
  LPPC/ASR/LPPT_GND_TSGR.asr
  LPPC/Settings/DepartureList_TopSky.txt
  LPPC/Settings/General.txt
  LPPC/Settings/Tags.txt
  topsky/TopSkyAreas.txt
  topsky/TopSkyAreasManualAct.txt
  topsky/TopSkySettings.txt
  topsky/TopSkySettingsLocal.txt
Labels: Feature, Tweak

#72 USAFE2020 areas
  topsky/TopSkyAreas.txt
  topsky/TopSkyAreasManualAct.txt
Labels: Feature

#73 clownfish
  topsky/TopSkyAreas.txt
  topsky/TopSkyAreasManualAct.txt
Labels: Fix

#74 Turns topsky assr logic back on
  topsky/TopSkySettings.txt
Labels: Fix
