Repository pinatacolada/topskylppc, pull requests merged in 2020-11, with the labels that each got.

#176 Update TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature, Fix, Tweak

#178 Fixes cascais being legally blind
  LPPC/ASR/LPCS_TWR.asr
Labels: Fix

#180 Fixes Canarias frequencies not showing
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#181 Real Thaw areas
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Feature

#182 RT20 reroutes
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#183 Update readme pictures
  README.md
Labels: Documentation

#184 world largest pr
  README.md
Labels: Fix, Working as Intended™

#185 Fixes random radar target symbology
  LPPC/Settings/Symbology_TopSky.txt
Labels: Fix

#186 Update docs to 1.4
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.docx
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.pdf
Labels: Documentation

#187 FUA
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#188 Ground radar example local settings
  LPPC/Plugins/topsky/GRpluginSettingsLocal.txt
Labels: Feature

#189 Fixes notams not getting detected
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix

#190 FUA
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#192 Update TopSkySettings.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#191 Update Tags_TopSky.txt
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#194 Areas update
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Feature, Tweak

#195 Fixes overlapping labels in cascais
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#193 Update TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#196 Fixes southern spain being swallowed by the atlantic ocean
  LPPC/ASR/LPPC_CTR_TS.asr
Labels: Fix

#197 Reduce usage of LPPR apron W
  LPPC/Plugins/topsky/GRpluginStands.txt
Labels: Fix

#198 Add lvp option to atis
  LPPC/Settings/General_TopSky.txt
Labels: Tweak

#201 Update GRpluginMaps.txt
  LPPC/Plugins/topsky/GRpluginMaps.txt
Labels: Tweak

#202 Update TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#203 Display stand in approach window labels
  LPPC/Plugins/topsky/GRpluginSettings.txt
Labels: Feature

#204 Ground Radar 1.4.3
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - Developer Guide.pdf
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - General.pdf
  LPPC/Plugins/topsky/Documentation/Ground Radar plugin for EuroScope - Version History.pdf
  LPPC/Plugins/topsky/GRplugin.dll
  LPPC/Plugins/topsky/GRpluginOperatorInfo.txt
  LPPC/Plugins/topsky/GRpluginSettings.txt
Labels: Fix, Update

#205 Update TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#206 1 SPACE
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Fix
