Repository pinatacolada/topskylppc, pull requests merged in 2021-02, with the labels that each got.

#222 New LPMA TMA
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#230 oops
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#232 Fixes CEU and COU level map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#233 Add 122.8 CPDLC message
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Feature

#235 FSM Header
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#236 Update TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Fix

#238 Spacing and timing
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix, Tweak
