Repository pinatacolada/topskylppc, pull requests merged in 2021-12, with the labels that each got.

#285 Fix runway 35 error message
  LPPC/Plugins/topsky/GRpluginSettings.txt
Labels: Fix

#286 Update stands data
  LPPC/Plugins/topsky/GRpluginStands.txt
Labels: Tweak

#287 Update README.md 147
  README.md
Labels: Documentation

#288 Fixes LPPR taxiway names
  LPPC/Plugins/topsky/GRpluginMaps.txt
Labels: Fix

#289 Fixes the fix of LPPR taxiway names
  LPPC/Plugins/topsky/GRpluginMaps.txt
Labels: Fix

#290 update dcl format
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#281 CDM plugin
  LPPC/Plugins/ACDM/CDM.dll
  LPPC/Plugins/ACDM/CDMconfig.xml
  LPPC/Plugins/ACDM/colors.txt
  LPPC/Plugins/ACDM/rate.txt
  LPPC/Plugins/ACDM/taxizones.txt
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.docx
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.pdf
  LPPC/Settings/DepartureList_TopSky.txt
  LPPC/Settings/Plugins.txt
  LPPC_CTR_TS.prf
Labels: Feature

#291 Spain CPDLC codes
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Tweak

#292 Fixes Casablanca freqs
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#293 Update README.md
  README.md
Labels: Documentation

#294 Fixes ACDM not loading
  LPPC_CTR_TS.prf
Labels: Fix
