Repository pinatacolada/topskylppc, pull requests merged in 2021-03, with the labels that each got.

#241 GNG areas sync
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
Labels: Tweak

#242 RT2021
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Feature

#245 RT21 reroute
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#244 Fixes CPDLC window showing when not appropriate
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Plugins/topsky/TopSkySettingsLocal.txt
Labels: Fix

#243 Removes sector file automatically generated maps from Maps window
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#239 Update Madeira maps
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature, Fix, Tweak

#248 Refactor automatic maps
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Plugins/topsky/TopSkySettingsLocal.txt
Labels: Tweak

#249 Fixes invisible planes at LPFR and LPMA
  LPPC/ASR/LPFR_GND_TSGR.asr
  LPPC/ASR/LPMA_GND_TSGR.asr
  LPPC/Plugins/topsky/GRpluginSettings.txt
Labels: Fix
