Repository pinatacolada/topskylppc, pull requests merged in 2021-07, with the labels that each got.

#259 General aeronautical information updates
  LPPC/Plugins/topsky/GRpluginMaps.txt
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#261 LPPT stand fixes
  LPPC/Plugins/topsky/GRpluginStands.txt
Labels: Fix

#262 Add Area A to LPPT TMA map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#263 bye amsl
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak
