Repository pinatacolada/topskylppc, pull requests merged in 2022-08, with the labels that each got.

#310 assumed non concerned and notified colors
  LPPC/Settings/Symbology_TopSky.txt
Labels: Tweak

#311 Fix town_nl color
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#312 BENAV declutter
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#334 Update Areas_Label_Font
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#332 Update AIC according to latest info
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#335 Tricks ES to disable leaderlines
  LPPC/ASR/LPPC_CTR_TS.asr
Labels: Tweak

#339 new delagation areas dellis delfar
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#340 New LPPR delegation
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#341 New LPFR delegation
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#342 LPCS bug fixes
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature, Fix

#343 add topsky stca inhibit areas
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Feature

#344 Fixes CFL collumn
  LPPC/Settings/Plugins.txt
Labels: Fix

#345 Removes non ILS extended centerlines
  LPPC/Plugins/topsky/TopSkyAirspace.txt
Labels: Tweak

#346 Adds toggle frequency action on label
  LPPC/Settings/Tags_TopSky.txt
Labels: Feature

#347 Grey tweaks
  LPPC/Settings/Symbology_TopSky.txt
Labels: Fix

#350 cleans a bit ssr codes for civilian flights
  LPPC/Plugins/topsky/TopSkySSRcodes.txt
Labels: Not a bug, Tweak

#357 Update TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#358 Update TopSkySettings.txt
  LPPC/Plugins/topsky/TopSkyAirspace.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#360 update tag dest action
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#362 APW settings
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature

#363 METAR colors
  LPPC/Settings/Symbology_TopSky.txt
Labels: Fix

#365 adds vccs
  LPPC/Settings/VCCS.txt
Labels: Fix

#369 Update TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#368 symbology fixes
  LPPC/Settings/Symbology_TopSky.txt
Labels: Fix

#364 Label fixes
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#370 Fix missing TSAT actions
  LPPC/Settings/DepartureList_TopSky.txt
Labels: Fix

#372 List fixes
  LPPC/Settings/Plugins.txt
Labels: Fix
