Repository pinatacolada/topskylppc, pull requests merged in 2022-05, with the labels that each got.

#299 New areas handling
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyAreasManualAct.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature, Tweak

#303 Update LPPT Runway 02
  LPPC/Plugins/ACDM/rate.txt
  LPPC/Plugins/ACDM/taxizones.txt
  LPPC/Plugins/topsky/GRpluginMaps.txt
  LPPC/Plugins/topsky/GRpluginSettings.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#304 oops
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#305 Fixes LPPT GNSS maps
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix
