Repository pinatacolada/topskylppc, pull requests merged in 2022-12, with the labels that each got.

#557 sct ese and rwy gitignore
  .gitignore
Labels: DevOps

#554 Independant A-SMGCS radar source
  .gitignore
  LPPC/ASR/LPCS_TWR.asr
  LPPC/ASR/LPFR_GND_TSGR.asr
  LPPC/ASR/LPMA_GND_TSGR.asr
  LPPC/ASR/LPPC_CTR_TS.asr
  LPPC/ASR/LPPR_GND_TSGR.asr
  LPPC/ASR/LPPT_GND_TSGR.asr
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
  LPPC/Settings/General_TopSky.txt
Labels: Tweak

#560 Delete LPPC/Plugins/topsky/bigcursors unused directory
  LPPC/Plugins/topsky/bigcursors/arrowleft.cur
  LPPC/Plugins/topsky/bigcursors/arrowright.cur
  LPPC/Plugins/topsky/bigcursors/cross.cur
  LPPC/Plugins/topsky/bigcursors/move.cur
  LPPC/Plugins/topsky/bigcursors/resize.cur
  LPPC/Plugins/topsky/bigcursors/stop.cur
Labels: Revert/Removal

#563 Implements DIAS and DMACH DAPs
  LPPC/Plugins/IASsure/IASsure.dll
  LPPC/Plugins/IASsure/config.json
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Settings/Tags_TopSky.txt
  LPPC_CTR_TS.prf
Labels: Documentation, Feature

#559 Initial MSAW implementation
  LPPC/Plugins/topsky/TopSkyMSAW.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature, Tweak

#567 Updates METAR and NOTAM API URL
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#572 Reverts to EuroScope ground radar sources
  .gitignore
  LPPC/ASR/LPPC_CTR_TS.asr
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
  LPPC/Settings/General_TopSky.txt
Labels: Revert/Removal, Fix
