Repository pinatacolada/topskylppc, pull requests merged in 2022-09, with the labels that each got.

#373 Reverts to default shortcuts
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Revert/Removal

#374 Map fixes
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature, Fix

#379 Fixes DAP label settings
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#380 Unselected tag fix
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#384 Unselected TOG
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#381 Area fixes
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#389 Adds missing unselected label toggles
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#395 fix del norte lppt tma
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#394 Assorted area fixes
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#397 Areas tidy up
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#398 change mil apron stand name
  LPPC/Plugins/topsky/GRpluginStands.txt
Labels: Tweak

#400 fix freq not auto showing on label
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#401 Adds more rows to Sector list
  LPPC/Settings/Plugins.txt
Labels: Feature

#404 Minor fixes
  LPPC/Settings/General_TopSky.txt
Labels: Fix

#402 FCOPX consistency
  LPPC/Settings/Tags_TopSky.txt
Labels: Tweak

#405 Minor window position adjustments
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Settings/DepartureList_TopSky.txt
  LPPC/Settings/Screen_TopSky.txt
Labels: Tweak

#406 Anchors to line 1 first element
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#408 Updates LPPT taxiway restrictions
  LPPC/Plugins/topsky/GRpluginMaps.txt
Labels: Feature

#409 Shore and river maps
  LPPC/ASR/LPPC_CTR_TS.asr
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature

#411 Fix changelog
  .github/release.yml
Labels: DevOps

#430 Adds missing plugins
  LPPC_CTR_TS.prf
Labels: Fix

#426 enables atis freq and vccs display
  LPPC/Settings/Screen_TopSky.txt
  LPPC_CTR_TS.prf
Labels: Fix

#438 Update RAM Divergence threshold
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#439 Updates Safety Nets parameters
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#440 Adds CPDLC freetext messages
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Feature

#442 Updates CDM version to 2.0.9
  LPPC/Plugins/ACDM/CDM.dll
  LPPC/Plugins/ACDM/CDMconfig.xml
  LPPC/Settings/DepartureList_TopSky.txt
Labels: Update

#444 Fixes jumping tag issues
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#445 Adds bandbox map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#446 Fix Demos sector kink
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#447 Adds known issues to changelogs
  .github/release.yml
Labels: DevOps

#448 Moves GroundRadar to own folder
  LPPC/Plugins/GroundRadar/Documentation/Ground Radar plugin for EuroScope - Developer Guide.pdf
  LPPC/Plugins/GroundRadar/Documentation/Ground Radar plugin for EuroScope - General.pdf
  LPPC/Plugins/GroundRadar/Documentation/Ground Radar plugin for EuroScope - Version History.pdf
  LPPC/Plugins/GroundRadar/GRplugin.dll
  LPPC/Plugins/GroundRadar/GRpluginAircraftInfo.txt
  LPPC/Plugins/GroundRadar/GRpluginCallsigns.txt
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
  LPPC/Plugins/GroundRadar/GRpluginOperatorInfo.txt
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
  LPPC/Plugins/GroundRadar/GRpluginSettingsLocal.txt
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
  LPPC_CTR_TS.prf
Labels: Tweak

#450 add comment about rwy marking
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Tweak
