Repository pinatacolada/topskylppc, pull requests merged in 2022-11, with the labels that each got.

#487 Update TopSkyCPDLC and Maps for new ES IDs
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#488 Update R60A label position
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix

#489 Updates LPPR RVA
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#499 CAD Portugal
  LPPC/Plugins/ACDM/CAD/CAD_Portugal.txt
Labels: Feature

#498 Track label fixes
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#502 EuroScope Installation Guide
  _config.yml
  assets/img/admin.png
  assets/img/aload.png
  assets/img/cancel.png
  assets/img/complete.png
  assets/img/dl.png
  assets/img/dlar.png
  assets/img/dlcomplete.png
  assets/img/dlup.png
  assets/img/prof.png
  assets/img/ptdld.png
  assets/img/ptinst.png
  assets/img/rclick.png
  assets/img/sf1.png
  assets/img/sf2.png
  assets/img/sf3.png
  assets/img/short.png
  index.md
Labels: Documentation, DevOps

#511 Fixes APW for VFR
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#514 Update track control settings
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#516 Fixes WTC not showing in unselected labels
  LPPC/Settings/Tags_TopSky.txt
Labels: Fix

#517 Restores flight leg by RMB in FCOPX
  LPPC/Settings/Tags_TopSky.txt
Labels: Tweak

#519 Sets CFL and DCT defaults to voice for APP positions
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#523 Set max usable flight level in lists to F650
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#525 Removes old files
  LPPC/Plugins/topsky/TopSkyCPDLCsound.wav
  LPPC/Plugins/topsky/TopSkyCoordSound.wav
  LPPC/Plugins/topsky/TopSkyCoordSoundACP.wav
  LPPC/Plugins/topsky/TopSkyCoordSoundRJC.wav
  LPPC/Plugins/topsky/TopSkySTCAsound.wav
  LPPC/Plugins/topsky/arrowleft.cur
  LPPC/Plugins/topsky/arrowright.cur
  LPPC/Plugins/topsky/cross.cur
  LPPC/Plugins/topsky/move.cur
  LPPC/Plugins/topsky/resize.cur
  LPPC/Plugins/topsky/stop.cur
Labels: Fix

#524 Fixes CARD, MTCD and RAM limits and settings
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#527 Tidies Documentation Folder
  LPPC/Plugins/topsky/Documentation/Original Documentation/TopSky plugin for EuroScope - Coordination.pdf
  LPPC/Plugins/topsky/Documentation/Original Documentation/TopSky plugin for EuroScope - Data Link Functions.pdf
  LPPC/Plugins/topsky/Documentation/Original Documentation/TopSky plugin for EuroScope - Developer Guide.pdf
  LPPC/Plugins/topsky/Documentation/Original Documentation/TopSky plugin for EuroScope - General.pdf
  LPPC/Plugins/topsky/Documentation/Original Documentation/TopSky plugin for EuroScope - Version History.pdf
  LPPC/Plugins/topsky/Documentation/Original Documentation/TopSky_Developer_Guide_Settings.xlsx
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.docx
  LPPC/Plugins/topsky/Documentation/TopSky plugin for EuroScope - Portugal.pdf
Labels: Documentation

#528 updates tfc management and uncon lists
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS Manual.pdf
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Settings/Plugins.txt
Labels: Documentation, Tweak

#530 updates clsd twy at lppt
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Fix

#532 update vccs server
  LPPC/Settings/VCCS.txt
Labels: Fix

#534 Fixes missing callsigns in GR
  LPPC/Plugins/GroundRadar/GRpluginAircraftInfo.txt
  LPPC/Plugins/GroundRadar/ICAO_Aircraft.json
  LPPC/Plugins/GroundRadar/ICAO_Airlines.txt
Labels: Fix

#536 Updates LPPT stand assignment rules
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Update

#539 Adds variable document titles
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/Latex/styles/ptvacc.sty
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
Labels: DevOps

#541 Update ATIS URL
  LPPC/Settings/General_TopSky.txt
Labels: Tweak

#547 Update .version
  .version
Labels: DevOps

#550 Adds FLeg display to RMB on MTCD Indicator
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Settings/Tags_TopSky.txt
Labels: Documentation, Tweak

#551 Updates VCCS
  LPPC/Settings/VCCS.txt
Labels: Fix

#552 Update rwy numbers in LPPT ground radar view
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Fix

#529 Fixes Madrid, Sevilla and Canarias CPDLC
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Fix

#553 Fixes GCCC logons
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Fix
