Repository pinatacolada/topskylppc, pull requests merged in 2022-10, with the labels that each got.

#456 update readme for toplis implementation
  README.md
Labels: Documentation

#458 Remove U weight restrictions
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Fix

#467 rate updated to 26deps/h
  LPPC/Plugins/ACDM/rate.txt
Labels: Tweak

#463 Refactor history dot symbol
  LPPC/Plugins/topsky/TopSkySymbols.txt
Labels: Tweak

#460 update track control settings + map loading tweaks + AIW and misc settings
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#469 Adds CPDLC support for TMAs and free text updates
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature, Tweak

#455 moves map definition to sct file + misc map improvements
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#473 Version keeping
  .dependencies
  .version
Labels: DevOps

#474 Update CDM to version 2.0.12
  .dependencies
  LPPC/Plugins/ACDM/CDM.dll
Labels: Update

#477 Test json manifest
  manifest.json
Labels: DevOps

#478 test2
  manifest.json
Labels: DevOps

#479 comma
  manifest.json
Labels: DevOps

#482 Better version control on readme
  README.md
Labels: DevOps

#483 Include beta releases in readme version
  README.md
Labels: DevOps

#485 Updates CDM to 2.0.13
  .dependencies
  LPPC/Plugins/ACDM/CDM.dll
  README.md
Labels: Update
