Repository pinatacolada/topskylppc, pull requests merged in 2023-04, with the labels that each got.

#651 Adds AirSerbia and Volotea to stand assignment rules
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#648 Iassure update 1.5.0
  LPPC/Plugins/IASsure/IASsure.dll
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Settings/Tags_TopSky.txt
  README.md
Labels: Documentation, Update

#653 Filter out non-departed tracks until ground state DEPA
  .gitignore
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix
