Repository pinatacolada/topskylppc, pull requests merged in 2023-02, with the labels that each got.

#603 More scalable TML default
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#606 Corrects town symbol
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#608 Updates TRA13 and D65 label
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#609 Updates displayed towns in town map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#615 Update CDM to 2.1.1
  .gitignore
  LPPC/Plugins/ACDM/CDM.dll
  LPPC/Plugins/ACDM/CDMconfig.xml
  LPPC/Plugins/ACDM/rate.txt
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  README.md
Labels: Documentation, Update

#614 Map updates
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#616 Updates to cdm 2.1.1
  .dependencies
Labels: DevOps

#617 Updates IASsure to 1.4.1
  .dependencies
  LPPC/Plugins/IASsure/IASsure.dll
  LPPC/Plugins/IASsure/LICENSE
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/refs.bib
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  README.md
Labels: Documentation, Update, DevOps

#621 Fixes GRPlugin comments syntax
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
Labels: Fix

#624 Update wx api url
  LPPC/Plugins/IASsure/config.json
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak
