Repository pinatacolada/topskylppc, pull requests merged in 2023-03, with the labels that each got.

#626 Removes wingspan restriction W2 W3
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Tweak

#628 Fixes LPPT A3 missing wingspan restriction
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Fix

#633 Update SAP buffers
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak, Fix

#634 Updates R60BU with new delegation
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#636 Temporary fix for vertical separation of RVSM areas
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix, Temporary

#619 More maps updates
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#629 Updates stand wingspan restrictions
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#639 latex compiler job
  .github/workflows/main.yml
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
Labels: DevOps

#642 Fixes latex job
  .github/workflows/main.yml
Labels: DevOps

#640 Updates IASSure to 1.4.2
  LPPC/Plugins/IASsure/IASsure.dll
  LPPC/Settings/Tags_TopSky.txt
  README.md
Labels: Update, Fix

#623 Updates/Improves current uncontrolled symbol
  LPPC/Plugins/topsky/TopSkySymbols.txt
Labels: Tweak

#644 Updates CDM to 2.2.0
  LPPC/Plugins/ACDM/CDM.dll
  LPPC/Plugins/ACDM/CDMconfig.xml
Labels: Update

#645 Update readme
  README.md
Labels: DevOps

#646 Fixes SI collumns being too smol
  LPPC/Settings/Plugins.txt
Labels: Fix
