Repository pinatacolada/topskylppc, pull requests merged in 2023-01, with the labels that each got.

#570 Update RTV areas color
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#574 New and final vccs server
  LPPC/Settings/VCCS.txt
Labels: Tweak

#575 Updated ATIS URL
  LPPC/Settings/General_TopSky.txt
Labels: Tweak

#576 Adds Croatia to Schengen area
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
Labels: Tweak

#577 Implements own weather provider
  LPPC/Plugins/IASsure/config.json
Labels: Tweak

#580 Fixes TML2 ETO
  LPPC/Settings/Plugins.txt
Labels: Fix

#583 Updates DEL LIS maps
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#579 Update MAX QDM as per B3.7
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#584 General update to areas
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#585 Removes Message Out window
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#586 Move Message In Window to bottom of screen
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#589 Adds FTM to P_TMA map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#597 Updates LPPR and LPPT LFUNCs references
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Settings/VCCS.txt
Labels: Tweak

#596 Removes list options from global menu
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#595 Updates area labels
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#594 Activates LPAR rwy display
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#593 Corrects LPMA init CFL for GALOZ and NIDUL SIDs
  LPPC/Plugins/topsky/TopSkyAirspace.txt
Labels: Fix

#600 Topsky Symbols Improvements
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/img/rps_ssr_unc.png
  LPPC/Plugins/topsky/Documentation/TOPLIS Manual.pdf
  LPPC/Plugins/topsky/TopSkySymbols.txt
Labels: Documentation, Tweak

#601 Adds comm type indicator to GR labels
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
Labels: Feature
