Repository pinatacolada/topskylppc, pull requests merged in 2024-07, with the labels that each got.

#759 Add Estrela area Real Beja and Sintra areas update
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#762 Resectorisation list Position column
  LPPC/Settings/Plugins.txt
Labels: Fix

#761 FPCA and STCA areas
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/TOPLIS Manual.pdf
Labels: Feature

#763 APS settings
  LPPC APS.prf
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Settings/DepartureList_TopSky_APS.txt
  LPPC/Settings/Plugins_APS.txt
  LPPC/TOPLIS Manual.pdf
Labels: Feature

#764 Independent Holding lists for typical HP
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature

#766 Add fixed medical helicopter squawks
  LPPC/Plugins/topsky/TopSkySSRcodes.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature

#768 ACS settings
  LPPC ACS.prf
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Settings/DepartureList_TopSky_ACS.txt
  LPPC/Settings/Plugins_ACS.txt
  LPPC/TOPLIS Manual.pdf
Labels: Feature

#770 Automatically check for merge conflicts
  .github/workflows/checkconflicts.yml
Labels: DevOps

#771 Remove deprecated TOPLIS tagfamily
  LPPC/Settings/Tags_TopSky.txt
Labels: Revert/Removal

#772 Adjust aerod, aerod_m and heli map label position
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#773 Refactor GR LPPT stand assignments
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak
