Repository pinatacolada/topskylppc, pull requests merged in 2024-08, with the labels that each got.

#778 B77W compatible LPPR stand restrictions
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#776 A380 support for LPPT
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Feature, LACK OF REALISM

#779 Auto activate LPPT STAR maps on LPPT_APP logins
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#780 Add missing airlines to LPPT stand rules
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#767 Update GMMM CPDLC logons
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
Labels: Tweak

#782 Remove unused git version files
  .dependencies
  .version
Labels: DevOps

#783 Remove working_areas map
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Revert/Removal

#785 Update documentation references
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/refs.bib
  LPPC/TOPLIS Manual.pdf
Labels: Documentation

#788 Remove LPPC_CTR_TS.prf
  LPPC_CTR_TS.prf
Labels: Revert/Removal

#787 Update installation instructions with new prfs
  assets/img/prof.png
  index.md
Labels: Documentation

#796 Add LPVZ groundlayout
  LPPC/ASR/LPCS_TWR.asr
Labels: Feature
