Repository pinatacolada/topskylppc, pull requests merged in 2024-10, with the labels that each got.

#819 Wrong ATIS frequencies
  LPPC ACS.prf
  LPPC APS.prf
Labels: Fix

#820 New ATIS source
  LPPC ACS.prf
  LPPC APS.prf
  LPPC/Settings/General_TopSky.txt
Labels: Feature

#818 VCCS LPPR GND
  LPPC/Settings/VCCS.txt
Labels: Feature

#821 Add British Airways subsidiaries to Ground Radar
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#822 Add Icelandair to LPPT stands
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#823 Update mode S capable codes
  LPPC/Settings/General_TopSky.txt
Labels: Tweak

#824 Revert "Temporary Capacity reduction CAD LPPT (#735)"
  LPPC/Plugins/ACDM/CAD/CAD_Portugal.txt
Labels: Revert/Removal

#826 atis lvo parameters
  LPPC ACS.prf
  LPPC APS.prf
Labels: Fix

#825 VATSIM-UK/uk-controller-pack Euroscope sounds
  .gitignore
  LPPC ACS.prf
  LPPC APS.prf
  LPPC/Sounds/atc_message.wav
  LPPC/Sounds/broadcast_message.wav
  LPPC/Sounds/conflict_alert.wav
  LPPC/Sounds/connected.wav
  LPPC/Sounds/disconnected.wav
  LPPC/Sounds/handoff_accept.wav
  LPPC/Sounds/handoff_refused.wav
  LPPC/Sounds/handoff_request.wav
  LPPC/Sounds/landline_request.wav
  LPPC/Sounds/new_atis.wav
  LPPC/Sounds/ongoing_accepted.wav
  LPPC/Sounds/ongoing_manual.wav
  LPPC/Sounds/ongoing_refused.wav
  LPPC/Sounds/ongoing_request.wav
  LPPC/Sounds/pointout.wav
  LPPC/Sounds/private_message.wav
  LPPC/Sounds/radio_message.wav
  LPPC/Sounds/reminder.wav
  LPPC/Sounds/startup.wav
  LPPC/Sounds/supervisor_message.wav
  LPPC_CTR.prf
Labels: Feature

#827 Duplicated stand rules LPPT 108
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Fix

#828 Disable LPPT stand 108 auto assignment
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak, Temporary

#829 Disable LPPT stand 223 auto assignment
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak, Temporary

#831 Update README.md
  README.md
Labels: Documentation

#832 Add LPPM responsability and comms transfer area map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature
