Repository pinatacolada/topskylppc, pull requests merged in 2024-11, with the labels that each got.

#834 GR LPPR safety nets settings corruption
  LPPC/Plugins/GroundRadar/GRpluginSettings.txt
Labels: Fix

#833 WF24 EventStands
  LPPC/Plugins/GroundRadar/GRpluginEventStands.txt
Labels: Temporary

#839 Update TopSkyAreas
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#841 Add distance to Vector_AHDG
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#840 Flightleg update
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#842 Update PLC reminder time value
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#846 Reverts FlightLeg pixel changes
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Revert/Removal
