Repository pinatacolada/topskylppc, pull requests merged in 2024-05, with the labels that each got.

#738 Revert "Reopen T2"
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
Labels: Revert/Removal

#739 New LPPT RVA
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Feature

#740 Declutter arr-app map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#741 Update LFUNC and GNG Sct names
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Settings/VCCS.txt
Labels: Tweak

#742 Missing UNPOT from rep_cas_star
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#744 LPPT departure capacity reduction
  LPPC/Plugins/ACDM/CDMconfig.xml
Labels: Tweak, Temporary

#743 LPPT Point Merge System
  LPPC/Plugins/ACDM/CAD/CAD_Portugal.txt
  LPPC/Plugins/ACDM/CDMconfig.xml
  LPPC/Plugins/GroundRadar/GRpluginMaps.txt
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/Plugins/topsky/TopSkyMaps.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
  LPPC/Settings/VCCS.txt
Labels: Feature

#745 VCCS missing military LFUNC
  LPPC/Settings/VCCS.txt
Labels: Fix

#746 New LPPT and LPCS initial climb
  LPPC/Plugins/topsky/TopSkyAirspace.txt
Labels: Tweak

#748 Missing traffic management list setting for LPPT_APP
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Fix

#751 LIS APP View
  LPPC/Plugins/topsky/TopSkyViews.txt
Labels: Fix

#752 New AIRAC 2405 procedures MIL maps (LPMT, LPST, LPBJ)
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak
