Repository pinatacolada/topskylppc, pull requests merged in 2024-12, with the labels that each got.

#845 AFL highlight
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Settings/Tags_TopSky.txt
  LPPC/TOPLIS Manual.pdf
Labels: Feature

#849 XFL Level Band Highlight
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Settings/Tags_TopSky.txt
  LPPC/TOPLIS Manual.pdf
Labels: Feature

#850 Move LED125 label
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak

#851 AMC areas via AUP
  LPPC/Plugins/topsky/TopSkyAreas.txt
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Feature

#852 Fix LPPT non Schengen flights assigned to stands 124 125
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Fix

#853 Several TSA updates
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Tweak, Revert/Removal, Fix

#855 STAND S42 UPGRADED TO B77L.
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak, Temporary

#856 Refactor LPPR and LPFR stands to use STANDLIST
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#857 Comment activation on DST
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix

#858 Remove unused .sct location in .asr files
  LPPC/ASR/LPFR_TWR.asr
  LPPC/ASR/LPMA_TWR.asr
  LPPC/ASR/LPPC_CTR_TS.asr
Labels: Tweak

#859 Adds Canarias-Agadir border and Sintra delegation to adj_fir_sec map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#861 Estrela area name
  LPPC/Plugins/topsky/TopSkyAreas.txt
Labels: Fix

#862 Protect CDM sensitive information with GitHub secrets
  .github/workflows/makerelease.yml
Labels: DevOps

#866 Disable CPDLC by default
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Revert/Removal

#867 Automate releases
  .github/workflows/makerelease.yml
Labels: DevOps

#868 autorel2
  .github/workflows/makerelease.yml
Labels: DevOps

#869 autorel3
  .github/workflows/makerelease.yml
Labels: DevOps

#870 autorel4
  .github/workflows/makerelease.yml
Labels: DevOps

#871 autorel5
  .github/workflows/makerelease.yml
Labels: DevOps

#872 autorel6
  .github/workflows/makerelease.yml
Labels: DevOps

#875 new WPT TOFEF, WPT PORLI withdrawn
  LPPC/ASR/LPPC_CTR.asr
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak
