Repository pinatacolada/topskylppc, pull requests merged in 2025-01, with the labels that each got.

#876 LPCS new taxiway layout
  LPPC/ASR/LPCS_TWR.asr
Labels: Feature

#877 Add FRASO and FGUIA to pcas map
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Tweak

#881 SMAOCA frequency
  LPPC/Plugins/topsky/TopSkyMaps.txt
Labels: Fix

#883 DRC DAPs on unselected labels in APP and TWR
  LPPC/Plugins/topsky/TopSkySettings.txt
Labels: Tweak

#885 Add LOT to LPPT T1
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#886 Add EDW to LPPT stand rules
  LPPC/Plugins/GroundRadar/GRpluginStands.txt
Labels: Tweak

#891 Add new CPDLC freetext messages
  LPPC/Plugins/topsky/Documentation/Latex/TOPLIS/TOPLIS Manual.tex
  LPPC/Plugins/topsky/TopSkyCPDLC.txt
  LPPC/TOPLIS Manual.pdf
Labels: Feature
